Repository pupil-labs/pupil, pull requests merged in 2019-07, with the labels that each got.

#1552 Remove boost dependency
  pupil_src/shared_cpp/include/logger/pycpplogger.h
  pupil_src/shared_cpp/include/math/intersect.h
  pupil_src/shared_modules/calibration_routines/optimization_calibration/setup.py
  pupil_src/shared_modules/pupil_detectors/setup.py
  pupil_src/shared_modules/pupil_detectors/singleeyefitter/EyeModelFitter.cpp
  pupil_src/shared_modules/pupil_detectors/singleeyefitter/EyeModelFitter.h
  pupil_src/shared_modules/pupil_detectors/singleeyefitter/fun.h
  pupil_src/tests/LoggerTest/build_and_run_test.py
  pupil_src/tests/LoggerTest/loggerTest.cpp
Labels: Windows, enhancement

#1554 Disable Stripe Detector for Pupil Cam3
  pupil_src/shared_modules/video_capture/uvc_backend.py
Labels: bug

#1559 GLFW: Raise with detailed error message
  pupil_src/shared_modules/glfw.py
Labels: enhancement

#1563 Sample pupil timelines with float32 precision
  pupil_src/shared_modules/pupil_producers.py
Labels: bug, enhancement
