Repository pupil-labs/pupil, pull requests merged in 2019-10, with the labels that each got.

#1666 Player drop: Implement multi-line tip
  pupil_src/launchables/player.py
Labels: enhancement

#1667 V1.16 fixes
  pupil_src/shared_modules/gaze_producer/model/calibration_storage.py
  pupil_src/shared_modules/gaze_producer/ui/storage_edit_menu.py
  pupil_src/shared_modules/pupil_recording/recording.py
  pupil_src/shared_modules/storage.py
  pupil_src/shared_modules/video_export/plugins/imotions_exporter.py
Labels: bug

#1668 Support pre v1.3/r0.21.0 recordings in v1.16
  pupil_src/shared_modules/pupil_recording/update/mobile.py
  pupil_src/shared_modules/pupil_recording/update/old_style.py
Labels: expert

#1675 Save eye movements to disk when detection is completed
  pupil_src/shared_modules/eye_movement/eye_movement_detector_offline.py
Labels: bug

#1678 Export homography matrices for transforming between distorted image and surface coordinates
  pupil_src/shared_modules/surface_tracker/background_tasks.py
  pupil_src/shared_modules/surface_tracker/surface.py
Labels: API changes, enhancement

#1681 Bugfixes
  pupil_src/launchables/eye.py
  pupil_src/shared_modules/pupil_recording/recording.py
Labels: bug

#1679 Add version cli argument
  pupil_src/main.py
  pupil_src/shared_modules/launchable_args.py
Labels: enhancement

#1692 Fix surface corner drag inaccuracies
  pupil_src/shared_modules/surface_tracker/surface.py
Labels: bug

#1694 Scale heatmap export based on surface size
  pupil_src/shared_modules/surface_tracker/background_tasks.py
Labels: enhancement

#1693 Support streaming Pupil Invisible camera
  pupil_src/shared_modules/video_capture/ndsi_backend.py
Labels: enhancement

#1697 Fix heatmap history length setter not working
  pupil_src/shared_modules/surface_tracker/surface_online.py
  pupil_src/shared_modules/surface_tracker/surface_tracker_online.py
Labels: bug

#1701 Add missing dependencies for Ubuntu <=17
  docs/dependencies-ubuntu17.md
Labels: Linux, documentation

#1700 Support multiple AprilTag families and configurations
  pupil_src/shared_modules/surface_tracker/gui.py
  pupil_src/shared_modules/surface_tracker/offline_utils.py
  pupil_src/shared_modules/surface_tracker/surface_marker.py
  pupil_src/shared_modules/surface_tracker/surface_marker_detector.py
  pupil_src/shared_modules/surface_tracker/surface_tracker.py
  pupil_src/shared_modules/surface_tracker/surface_tracker_offline.py
Labels: enhancement

#1708 Do not catch system exceptions
  deployment/deploy_capture/finalize_bundle.py
  deployment/deploy_player/finalize_bundle.py
  deployment/deploy_service/finalize_bundle.py
  pupil_src/launchables/player.py
  pupil_src/launchables/service.py
  pupil_src/launchables/world.py
  pupil_src/shared_modules/batch_exporter.py
  pupil_src/shared_modules/calibration_routines/screen_marker_calibration.py
  pupil_src/shared_modules/calibration_routines/single_marker_calibration.py
  pupil_src/shared_modules/camera_intrinsics_estimation.py
  pupil_src/shared_modules/camera_models.py
  pupil_src/shared_modules/head_pose_tracker/storage/general_settings.py
  pupil_src/shared_modules/head_pose_tracker/storage/optimization_storage.py
  pupil_src/shared_modules/methods.py
  pupil_src/shared_modules/player_methods.py
  pupil_src/shared_modules/pupil_remote.py
  pupil_src/shared_modules/recorder.py
  pupil_src/shared_modules/square_marker_detect.py
  pupil_src/shared_modules/video_capture/ndsi_backend.py
  pupil_src/shared_modules/video_capture/uvc_backend.py
  pupil_src/shared_modules/vis_light_points.py
Labels: enhancement

#1713 Handle keyboard interrupts gracefully
  pupil_src/launchables/eye.py
  pupil_src/launchables/player.py
  pupil_src/launchables/service.py
  pupil_src/launchables/world.py
  pupil_src/shared_modules/background_helper.py
  pupil_src/shared_modules/gaze_producer/worker/create_calibration.py
  pupil_src/shared_modules/gaze_producer/worker/map_gaze.py
  pupil_src/shared_modules/os_utils.py
  pupil_src/shared_modules/tasklib/background/patches.py
  pupil_src/shared_modules/tasklib/manager.py
Labels: enhancement
