Repository pupil-labs/pupil, pull requests merged in 2019-12, with the labels that each got.

#1751 Correctly handle empty video files
  pupil_src/shared_modules/video_capture/utils.py
Labels: bug

#1752 Custom gl error
  pupil_src/shared_modules/gl_utils/utils.py
Labels: enhancement

#1756 Include missing dll dependencies in Windows bundle
  .gitignore
  deployment/bundle.bat
  deployment/deploy_capture/bundle.spec
  deployment/deploy_player/bundle.spec
  deployment/deploy_service/bundle.spec
  pupil_external/vc_redist/README.txt
Labels: Windows

#1642 Extract pupil_detectors into a separate repo
  deployment/bundle.bat
  deployment/bundle.sh
  pupil_src/launchables/eye.py
  pupil_src/shared_cpp/include/DistancePointEllipse.h
  pupil_src/shared_cpp/include/mathHelper.h
  pupil_src/shared_cpp/include/projection.h
  pupil_src/shared_cpp/include/solve.h
  pupil_src/shared_modules/calibration_routines/optimization_calibration/setup.py
  pupil_src/shared_modules/methods.py
  pupil_src/shared_modules/pupil_detector_plugins/__init__.py
  pupil_src/shared_modules/pupil_detector_plugins/detector_2d_plugin.py
  pupil_src/shared_modules/pupil_detector_plugins/detector_3d_plugin.py
  pupil_src/shared_modules/pupil_detector_plugins/detector_base_plugin.py
  pupil_src/shared_modules/pupil_detector_plugins/detector_dummy_plugin.py
  pupil_src/shared_modules/pupil_detector_plugins/manager.py
  pupil_src/shared_modules/pupil_detector_plugins/visualizer_2d.py
  pupil_src/shared_modules/pupil_detector_plugins/visualizer_3d.py
  pupil_src/shared_modules/pupil_detectors/.gitignore
  pupil_src/shared_modules/pupil_detectors/__init__.py
  pupil_src/shared_modules/pupil_detectors/build.py
  pupil_src/shared_modules/pupil_detectors/coarse_pupil.pxd
  pupil_src/shared_modules/pupil_detectors/detect_2d.hpp
  pupil_src/shared_modules/pupil_detectors/detector.pxd
  pupil_src/shared_modules/pupil_detectors/detector_2d.pyx
  pupil_src/shared_modules/pupil_detectors/detector_3d.pyx
  pupil_src/shared_modules/pupil_detectors/detector_dummy.py
  pupil_src/shared_modules/pupil_detectors/detector_utils.pxd
  pupil_src/shared_modules/pupil_detectors/setup.py
  pupil_src/shared_modules/pupil_detectors/singleeyefitter/CircleDeviationVariance3D.h
  pupil_src/shared_modules/pupil_detectors/singleeyefitter/CircleEvaluation3D.h
  pupil_src/shared_modules/pupil_detectors/singleeyefitter/CircleGoodness3D.h
  pupil_src/shared_modules/pupil_detectors/singleeyefitter/EllipseDistanceApproxCalculator.h
  pupil_src/shared_modules/pupil_detectors/singleeyefitter/EllipseDistanceResidualFunction.h
  pupil_src/shared_modules/pupil_detectors/singleeyefitter/EllipseEvaluation2D.h
  pupil_src/shared_modules/pupil_detectors/singleeyefitter/EyeModel.cpp
  pupil_src/shared_modules/pupil_detectors/singleeyefitter/EyeModel.h
  pupil_src/shared_modules/pupil_detectors/singleeyefitter/EyeModelFitter.cpp
  pupil_src/shared_modules/pupil_detectors/singleeyefitter/EyeModelFitter.h
  pupil_src/shared_modules/pupil_detectors/singleeyefitter/Fit/CircleOnSphereFit.h
  pupil_src/shared_modules/pupil_detectors/singleeyefitter/Fit/PlaneFit3D.h
  pupil_src/shared_modules/pupil_detectors/singleeyefitter/ImageProcessing/GuoHallThinner.h
  pupil_src/shared_modules/pupil_detectors/singleeyefitter/ImageProcessing/ImageContour.h
  pupil_src/shared_modules/pupil_detectors/singleeyefitter/ImageProcessing/cvx.cpp
  pupil_src/shared_modules/pupil_detectors/singleeyefitter/ImageProcessing/cvx.h
  pupil_src/shared_modules/pupil_detectors/singleeyefitter/LICENSE.md
  pupil_src/shared_modules/pupil_detectors/singleeyefitter/detectorUtils.cpp
  pupil_src/shared_modules/pupil_detectors/singleeyefitter/detectorUtils.h
  pupil_src/shared_modules/pupil_detectors/singleeyefitter/fun.h
  pupil_src/shared_modules/pupil_detectors/singleeyefitter/utils.cpp
  pupil_src/shared_modules/pupil_detectors/singleeyefitter/utils.h
  pupil_src/shared_modules/video_capture/base_backend.py
  pupil_src/shared_modules/video_capture/uvc_backend.py
  pupil_src/tests/pupil_detectors/__init__.py
  pupil_src/tests/pupil_detectors/test_distance_point_line.py
  pupil_src/tests/pupil_detectors/test_solve_npn.py
Labels: do not merge, expert

#1773 Pupil detectors docs
  docs/dependencies-macos.md
  docs/dependencies-ubuntu17.md
  docs/dependencies-ubuntu18.md
  docs/dependencies-windows.md
Labels: documentation

#1766 Only render detector debug views in algorithm mode
  pupil_src/shared_modules/pupil_detector_plugins/detector_2d_plugin.py
  pupil_src/shared_modules/pupil_detector_plugins/detector_3d_plugin.py
Labels: enhancement

#1770 Don't detect pupils when ROI out of frame bounds
  pupil_src/launchables/eye.py
  pupil_src/shared_modules/pupil_detector_plugins/detector_2d_plugin.py
  pupil_src/shared_modules/pupil_detector_plugins/detector_3d_plugin.py
Labels: bug

#1768 Adjust realsense loglevel
  pupil_src/shared_modules/video_capture/__init__.py
Labels: enhancement

#1776 Add pip upgrade instructions to README
  docs/dependencies-macos.md
  docs/dependencies-ubuntu17.md
  docs/dependencies-ubuntu18.md
  docs/dependencies-windows.md
Labels: documentation

#1767 Fix fullscreen calibration
  pupil_src/shared_modules/calibration_routines/screen_marker_calibration.py
  pupil_src/shared_modules/glfw.py
Labels: bug
