Repository pupil-labs/pupil, pull requests merged in 2019-08, with the labels that each got.

#1565 Pupil timeline sampling: Use pm.find_clostest to avoid IndexError
  pupil_src/shared_modules/pupil_producers.py
Labels: bug

#1573 Drop frames with 0 timestamp in uvc-backend
  pupil_src/shared_modules/video_capture/uvc_backend.py
Labels: Windows, bug

#1540 Surface tracker apriltag support
  pupil_src/launchables/player.py
  pupil_src/launchables/world.py
  pupil_src/shared_modules/apriltag.py
  pupil_src/shared_modules/apriltag_LICENSE.md
  pupil_src/shared_modules/head_pose_tracker/worker/detection_worker.py
  pupil_src/shared_modules/surface_tracker/__init__.py
  pupil_src/shared_modules/surface_tracker/background_tasks.py
  pupil_src/shared_modules/surface_tracker/cache.py
  pupil_src/shared_modules/surface_tracker/gui.py
  pupil_src/shared_modules/surface_tracker/offline_utils.py
  pupil_src/shared_modules/surface_tracker/surface.py
  pupil_src/shared_modules/surface_tracker/surface_marker.py
  pupil_src/shared_modules/surface_tracker/surface_marker_aggregate.py
  pupil_src/shared_modules/surface_tracker/surface_marker_detector.py
  pupil_src/shared_modules/surface_tracker/surface_offline.py
  pupil_src/shared_modules/surface_tracker/surface_online.py
  pupil_src/shared_modules/surface_tracker/surface_tracker.py
  pupil_src/shared_modules/surface_tracker/surface_tracker_offline.py
  pupil_src/shared_modules/surface_tracker/surface_tracker_online.py
Labels: feature request, priority:high

#1575 Add option to freeze current 3d eye model
  pupil_src/shared_cpp/include/common/types.h
  pupil_src/shared_modules/pupil_detectors/Tests/SphereCircleTests/VisualizeSphere.py
  pupil_src/shared_modules/pupil_detectors/__init__.py
  pupil_src/shared_modules/pupil_detectors/coarse_pupil.pxd
  pupil_src/shared_modules/pupil_detectors/detector.pxd
  pupil_src/shared_modules/pupil_detectors/detector_2d.pyx
  pupil_src/shared_modules/pupil_detectors/detector_3d.pyx
  pupil_src/shared_modules/pupil_detectors/setup.py
  pupil_src/shared_modules/pupil_detectors/singleeyefitter/EyeModel.cpp
  pupil_src/shared_modules/pupil_detectors/singleeyefitter/EyeModel.h
  pupil_src/shared_modules/pupil_detectors/singleeyefitter/EyeModelFitter.cpp
Labels: API changes, enhancement, feature request

#1577 v1.15 Fixes
  pupil_src/shared_modules/head_pose_tracker/worker/detection_worker.py
  pupil_src/shared_modules/surface_tracker/background_tasks.py
  pupil_src/shared_modules/surface_tracker/surface.py
  pupil_src/shared_modules/surface_tracker/surface_marker_detector.py
  pupil_src/shared_modules/surface_tracker/surface_tracker.py
  pupil_src/shared_modules/surface_tracker/surface_tracker_offline.py
  pupil_src/shared_modules/surface_tracker/surface_tracker_online.py
Labels: bug, enhancement
