Repository pupil-labs/pupil, pull requests merged in 2019-11, with the labels that each got.

#1682 Export pts in *_timstamps.csv file
  pupil_src/shared_modules/av_writer.py
Labels: API changes, enhancement

#1742 Fix bug #1691
  pupil_src/shared_modules/pupil_detectors/detector_2d.pyx
Labels: bug

#1743 Fixation detector fixes
  pupil_src/shared_modules/fixation_detector.py
Labels: API changes, bug

#1731 Temporal cutoffs in binocular gaze mapper based on estimated FPS
  pupil_src/shared_modules/calibration_routines/gaze_mappers.py
Labels: expert

#1747 Fix regression when fetching multi-part videos in VideoSet
  pupil_src/shared_modules/video_capture/utils.py
Labels: bug
