Repository pupil-labs/pupil, pull requests merged in 2019-06, with the labels that each got.

#1516 Export eye movements by gaze and by segment
  pupil_src/shared_modules/eye_movement/controller/__init__.py
  pupil_src/shared_modules/eye_movement/controller/eye_movement_csv_exporter.py
  pupil_src/shared_modules/eye_movement/eye_movement_detector_offline.py
  pupil_src/shared_modules/eye_movement/eye_movement_detector_real_time.py
  pupil_src/shared_modules/eye_movement/model/__init__.py
  pupil_src/shared_modules/eye_movement/model/color.py
  pupil_src/shared_modules/eye_movement/model/segment.py
  pupil_src/shared_modules/eye_movement/utils.py
  pupil_src/shared_modules/eye_movement/worker/real_time_buffered_detector.py
Labels: enhancement

#1515 Surface tracker improvements
  pupil_src/shared_modules/surface_tracker/background_tasks.py
  pupil_src/shared_modules/surface_tracker/cache.py
  pupil_src/shared_modules/surface_tracker/gui.py
  pupil_src/shared_modules/surface_tracker/surface.py
  pupil_src/shared_modules/surface_tracker/surface_offline.py
  pupil_src/shared_modules/surface_tracker/surface_tracker.py
  pupil_src/shared_modules/surface_tracker/surface_tracker_offline.py
Labels: API changes, bug, enhancement, priority:high

#1519 Remove deprecated detector plugins
  pupil_src/launchables/player.py
  pupil_src/launchables/world.py
  pupil_src/shared_modules/calibration_routines/manual_marker_calibration.py
  pupil_src/shared_modules/calibration_routines/screen_marker_calibration.py
  pupil_src/shared_modules/fixation_detector.py
  pupil_src/shared_modules/saccade_detector.py
  pupil_src/shared_modules/video_export/plugins/world_video_exporter.py
  pupil_src/shared_modules/vis_fixation.py
Labels: API changes

#1520 Allow passing Python lists as target to player_methods.find_clostest()
  pupil_src/shared_modules/player_methods.py
Labels: bug

#1527 Improve ui responsiveness
  pupil_src/launchables/eye.py
  pupil_src/launchables/player.py
  pupil_src/launchables/world.py
  pupil_src/shared_modules/service_ui.py
Labels: enhancement

#1523 Fixes for v1.13
  pupil_src/launchables/player.py
  pupil_src/launchables/world.py
  pupil_src/shared_modules/av_writer.py
  pupil_src/shared_modules/update_methods.py
Labels: bug

#1524 Add adapt_window_size notification handle in world process
  pupil_src/launchables/world.py
Labels: API changes
