Repository pupil-labs/pupil, pull requests merged in 2019-05, with the labels that each got.

#1503 Fix typo in file name and logs - positons to positions
  pupil_src/shared_modules/offline_reference_surface.py
  pupil_src/shared_modules/offline_surface_tracker.py
Labels: API changes

#1504 Use builtin types
  pupil_src/launchables/eye.py
  pupil_src/launchables/marker_detectors.py
  pupil_src/launchables/player.py
  pupil_src/launchables/service.py
  pupil_src/launchables/world.py
  pupil_src/shared_modules/file_methods.py
  pupil_src/shared_modules/fixation_detector.py
  pupil_src/shared_modules/gaze_producer/model/calibration_storage.py
  pupil_src/shared_modules/gaze_producer/worker/create_calibration.py
  pupil_src/shared_modules/gaze_producer/worker/map_gaze.py
  pupil_src/shared_modules/head_pose_tracker/worker/detection_worker.py
  pupil_src/shared_modules/marker_detector_cacher.py
  pupil_src/shared_modules/pupil_producers.py
  pupil_src/shared_modules/video_capture/tests/file_backend/test_file_backend.py
  pupil_src/shared_modules/video_export/plugin_base/isolated_frame_exporter.py
  pupil_src/shared_modules/video_overlay/workers/frame_fetcher.py
  pupil_src/shared_modules/vis_eye_video_overlay.py
Labels: enhancement, priority:medium

#1508 Remove deprecated vis_eye_video_overlay implementation
  pupil_src/shared_modules/video_export/plugins/eye_video_exporter.py
  pupil_src/shared_modules/vis_eye_video_overlay.py
Labels: enhancement, priority:medium

#1510 Fix Pupil Mobile intrinsics lookup
  pupil_src/shared_modules/video_capture/utils.py
Labels: bug

#1482 Eye movement detector
  .gitignore
  pupil_src/launchables/player.py
  pupil_src/launchables/world.py
  pupil_src/shared_modules/camera_models.py
  pupil_src/shared_modules/csv_utils.py
  pupil_src/shared_modules/eye_movement/__init__.py
  pupil_src/shared_modules/eye_movement/controller/__init__.py
  pupil_src/shared_modules/eye_movement/controller/eye_movement_csv_exporter.py
  pupil_src/shared_modules/eye_movement/controller/eye_movement_offline_controller.py
  pupil_src/shared_modules/eye_movement/controller/eye_movement_seek_controller.py
  pupil_src/shared_modules/eye_movement/eye_movement_detector_base.py
  pupil_src/shared_modules/eye_movement/eye_movement_detector_offline.py
  pupil_src/shared_modules/eye_movement/eye_movement_detector_real_time.py
  pupil_src/shared_modules/eye_movement/model/__init__.py
  pupil_src/shared_modules/eye_movement/model/color.py
  pupil_src/shared_modules/eye_movement/model/immutable_capture.py
  pupil_src/shared_modules/eye_movement/model/segment.py
  pupil_src/shared_modules/eye_movement/model/storage.py
  pupil_src/shared_modules/eye_movement/model/time_range.py
  pupil_src/shared_modules/eye_movement/ui/__init__.py
  pupil_src/shared_modules/eye_movement/ui/menu_content.py
  pupil_src/shared_modules/eye_movement/ui/navigation_buttons.py
  pupil_src/shared_modules/eye_movement/ui/segment_overlay.py
  pupil_src/shared_modules/eye_movement/utils.py
  pupil_src/shared_modules/eye_movement/worker/__init__.py
  pupil_src/shared_modules/eye_movement/worker/offline_detection_task.py
  pupil_src/shared_modules/eye_movement/worker/real_time_buffered_detector.py
  pupil_src/shared_modules/seek_control.py
  pupil_src/shared_modules/stdlib_utils.py
  pupil_src/shared_modules/tasklib/background/task.py
  pupil_src/shared_modules/tasklib/manager.py
  pupil_src/shared_modules/video_export/plugins/world_video_exporter.py
Labels: API changes, enhancement

#1511 Task_Proxy: Allow to specify multiprocessing context
  pupil_src/shared_modules/background_helper.py
Labels: Mac OS, enhancement, priority:high

#1514 Fix audio playback in cases where the audio is shorter than the world video
  pupil_src/shared_modules/audio_playback.py
Labels: bug
