Repository pupil-labs/pupil, pull requests merged in 2020-05, with the labels that each got.

#1860 Visualize available 2d and 3d pupil ellipses in eye overlay and eye video exporter
  pupil_src/shared_modules/video_export/plugins/eye_video_exporter.py
  pupil_src/shared_modules/video_overlay/plugins/eye_overlay.py
  pupil_src/shared_modules/video_overlay/utils/image_manipulation.py
Labels: type: enhancement

#1863 Confidence timeline: Fallback to 3d confidence if no 2d data is available
  pupil_src/shared_modules/pupil_producers.py
Labels: type: bug

#1877 Hide realsense cameras in camera selection list
  pupil_src/shared_modules/video_capture/uvc_backend.py
Labels: type: ui

#1871 Allow replacing `by_class` unique plugins
  pupil_src/shared_modules/plugin.py
Labels: API changes, type: enhancement

#1869 Remove system graph menu
  pupil_src/shared_modules/system_graphs.py
Labels: pr: do not merge

#1891 Resolve todos, publish gaze on ipc, and fix missing min_data_confidence attribute
  pupil_src/launchables/world.py
  pupil_src/shared_modules/fixation_detector.py
  pupil_src/shared_modules/gaze_mapping/gazer_2d.py
  pupil_src/shared_modules/gaze_mapping/gazer_base.py
  pupil_src/shared_modules/pupil_data_relay.py
Labels: type: bug
