Repository pupil-labs/pupil, pull requests merged in 2020-10, with the labels that each got.

#2027 Fix FPS drop on macOS for occluded windows
  pupil_src/launchables/eye.py
  pupil_src/launchables/world.py
Labels: os: macOS, type: bug

#2028 TS Lookup Table: Return unmodified ts if no invalid ts were found
  pupil_src/shared_modules/video_capture/utils.py
Labels: type: bug

#2025 Surface tracker stability improvements
  pupil_src/shared_modules/surface_tracker/offline_utils.py
  pupil_src/shared_modules/surface_tracker/surface_marker_detector.py
  pupil_src/shared_modules/surface_tracker/surface_tracker_offline.py
Labels: plugin: surface_tracker, type: bug
