Repository pupil-labs/pupil, pull requests merged in 2020-12, with the labels that each got.

#2059 Close eye window on crash
  pupil_src/launchables/eye.py
Labels: type: bug, type: enhancement

#2011 Remove 3D pupil detector
  docs/dependencies-macos.md
  docs/dependencies-ubuntu17.md
  docs/dependencies-ubuntu18.md
  pupil_src/launchables/eye.py
  pupil_src/shared_modules/pupil_detector_plugins/__init__.py
  pupil_src/shared_modules/pupil_detector_plugins/detector_2d_plugin.py
  pupil_src/shared_modules/pupil_detector_plugins/detector_3d_plugin.py
  pupil_src/shared_modules/pupil_detector_plugins/detector_base_plugin.py
  pupil_src/shared_modules/pupil_detector_plugins/pye3d_plugin.py
  pupil_src/shared_modules/pupil_detector_plugins/visualizer_3d.py
  requirements.txt
Labels: API changes

#2071 Fix stopping launcher via Network API
  pupil_src/main.py
Labels: type: bug

#2065 Use pye3d by default
  deployment/deploy_capture/bundle.spec
  deployment/deploy_player/bundle.spec
  deployment/deploy_service/bundle.spec
  pupil_src/shared_modules/blink_detection.py
  pupil_src/shared_modules/pupil_detector_plugins/detector_base_plugin.py
  pupil_src/shared_modules/pupil_detector_plugins/pye3d_plugin.py
  requirements.txt
Labels: API changes
