Repository pupil-labs/pupil, pull requests merged in 2020-06, with the labels that each got.

#1895 Allow to set ZMQ HWM for Eye Streams
  pupil_src/launchables/eye.py
  pupil_src/main.py
  pupil_src/shared_modules/zmq_tools.py
Labels: API changes, type: enhancement

#1905 Improve network api descriptions
  pupil_src/shared_modules/network_api/ui/frame_publisher_menu.py
  pupil_src/shared_modules/network_api/ui/pupil_remote_menu.py
Labels: type: documentation, type: enhancement

#1927 Fix MutableBisector.insert()
  pupil_src/shared_modules/player_methods.py
Labels: type: bug

#1928 Choreography plugins: Only call update_ui() in Capture
  pupil_src/shared_modules/calibration_choreography/base_plugin.py
  pupil_src/shared_modules/calibration_choreography/hmd_plugin.py
Labels: type: bug
