Repository pupil-labs/pupil, pull requests merged in 2020-11, with the labels that each got.

#2047 Fix minimizing 3d detector debug window on Windows OS
  pupil_src/shared_modules/gl_utils/trackball.py
Labels: os: Windows, type: bug, type: ui

#2050 Remove deprecated pye3d.geometry.eye import
  pupil_src/shared_modules/pupil_detector_plugins/__init__.py
  pupil_src/shared_modules/pupil_detector_plugins/visualizer_pye3d/__init__.py
Labels: type: bug

#2058 HMD Streaming: Support custom receiver high-water mark and set default value from None to 1
  pupil_src/shared_modules/video_capture/hmd_streaming.py
Labels: API changes
