Repository pupil-labs/pupil, pull requests merged in 2020-07, with the labels that each got.

#1949 Ensure frame publisher restarts when restarting NetworkAPIPlugin
  pupil_src/shared_modules/network_api/controller/frame_publisher_controller.py
  pupil_src/shared_modules/network_api/network_api_plugin.py
Labels: type: bug

#1948 Ignore macOS-specific meta files when using glob
  pupil_src/shared_modules/gaze_producer/model/legacy/calibration_storage_updater.py
  pupil_src/shared_modules/vis_watermark.py
Labels: os: macOS, type: bug

#1958 Coord_System: Avoid zero-width dimensions
  pupil_src/shared_modules/gl_utils/utils.py
Labels: type: bug, type: ui

#1965 Post-hoc gaze mapping: Avoid non-monotonic progress updates
  pupil_src/shared_modules/gaze_producer/worker/map_gaze.py
Labels: type: ui

#1966 Patch pyre.zhelper.cdll
  pupil_src/shared_modules/hololens_relay.py
  pupil_src/shared_modules/network_api/controller/pupil_remote_controller.py
  pupil_src/shared_modules/os_utils.py
  pupil_src/shared_modules/pupil_groups.py
  pupil_src/shared_modules/remote_recorder.py
  pupil_src/shared_modules/time_sync.py
  pupil_src/shared_modules/video_capture/ndsi_backend.py
Labels: os: macOS

#1983 Fix crash when calibrating 2D monocularly
  pupil_src/shared_modules/gaze_mapping/gazer_2d.py
Labels: type: bug
